### ISSUE TITLE
Support White/Blacklisting of Availability Zones

### ISSUE THREAD

**Issue by intersectRaven** [nautible/nautible-infra#68]
Right now, when I try to create a nautible cluster on 'ap-northeast-1', I encounter the ff. error:

```Error: creating EKS Cluster (nautible-dev-cluster-v1_29): operation error EKS: CreateCluster, https response error StatusCode: 400, RequestID: 3ed7bd71-56ae-46b2-bf89-380ad1e9d12a, UnsupportedAvailabilityZoneException: Cannot create cluster 'nautible-dev-cluster-v1_29' because EKS does not support creating control plane instances in ap-northeast-1b, the targeted availability zone. Retry cluster creation using control plane subnets that span at least two of these availability zones: ap-northeast-1a, ap-northeast-1c, ap-northeast-1d. Note, post cluster creation, you can run worker nodes in separate subnets/availability zones from control plane subnets/availability zones passed during cluster creation```

Please support either white/blacklisting availability zones. Right now, I worked around this error by blacklisting the zone in the vpc module's data.tf file:

```
data "aws_availability_zones" "available" {
  state = "available"
  exclude_names = ["ap-northeast-1b"]
}
```

**Comment by ogis-yamanaka** [comment]
exclude ap-northeast-1b
aws/platform/modules/vpc/data.tf

release 2024.2.0
